name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.16.1

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "22.19.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and package extension
        run: pnpm package

      - name: Get version from manifest.json
        id: version
        run: |
          VERSION=$(jq -r '.version' dist/manifest.json)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Version: ${VERSION}"

      - name: Create release package
        run: |
          # Rename the package.zip created by pnpm package
          mv package.zip newtab-v${{ steps.version.outputs.version }}.zip

          # Create a source code archive
          zip -r newtab-source-v${{ steps.version.outputs.version }}.zip . \
            -x "*.git*" \
            -x "*node_modules*" \
            -x "*release-package*" \
            -x "*.zip"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            newtab-v${{ steps.version.outputs.version }}.zip \
            newtab-source-v${{ steps.version.outputs.version }}.zip

      - name: Upload Release Assets Summary
        run: |
          {
            echo "### 📦 Release Created Successfully!"
            echo ""
            echo "**Version:** v${{ steps.version.outputs.version }}"
            echo "**Tag:** ${{ github.ref_name }}"
            echo ""
            echo "**Assets:**"
            echo "- \`newtab-v${{ steps.version.outputs.version }}.zip\` - Chrome Extension package"
            echo "- \`newtab-source-v${{ steps.version.outputs.version }}.zip\` - Source code"
          } >> "$GITHUB_STEP_SUMMARY"
